server:
  port: 7004
  servlet:
    context-path: /coupon-permission

spring:
  application:
    name: eureka-client-coupon-permission
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/asan_coupon_data?aotuReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      # 连接池最大连接数，默认是10
      maximum-pool-size: 8
      # 最小空闲连接数量
      minimum-idle: 4
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 45000
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: AsanCouponHikarri

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
