server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  #数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/asan_coupon_data?aotuReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

    #druid数据连接池的配置
    druid:
      filters: stat
      # 最大连接池数量
      maxActive: 20
      # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initialSize: 1
      # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      maxWait: 60000
      # 最小连接池数量
      minIdle: 1
      # Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      timeBetweenEvictionRunsMillis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的sql 因数据库方言而差,
      validationQuery: select 'x'
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      # 是否缓存preparedStatement，也就是PSCache。
      poolPreparedStatements: true
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      maxOpenPreparedStatements: 20
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    # Redis服务器连接密码（默认为空）
    #password:
    #连接超时时间
    timeout: 10000

mybatis:
  #  指定mapper的xml文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8000/eureka/

#-------------------------------监控信息-不一定要配置---------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: asan-coupon-template
    groupId: asan-coupon-service
    artifactId: coupon-template
    version: 1.0-SNAPSHOT
#---------------------------------------------------------------------------------------------------------------
logging:
  level:
    com.asan.coupon: debug